[workspace]
authors = ["Jacob H. Rothschild"]
channels = ["conda-forge"]
name = "robot-learning"
platforms = [{ platform = "osx-arm64", macos = "14.0" }]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.13"
wandb = ">=0.28.2,<0.29"

[pypi-dependencies]
lerobot = { version = ">=0.3.3, <0.4", extras = ["pusht"] }
